#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# build: Build related changes (eg: npm related/ adding external dependencies)
# chore: A code change that external user won't see (eg: change to .gitignore file or .prettierrc file)
# feat: A new feature
# fix: A bug fix
# docs: Documentation related changes
# refactor: A code that neither fix bug nor adds a feature. (eg: You can use this when there is semantic changes like renaming a variable/ function name)
# perf: A code that improves performance
# style: A code that is related to styling
# test: Adding new test or making changes to existing test

message="$(cat $1)"
requiredPattern="^(build:|chore:|feat:|fix:|docs:|refactor:|perf:|style:|test:) .*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo ""
  echo "▀███▀▀▀███▀███▀▀▀██▄ ▀███▀▀▀██▄   ▄▄█▀▀██▄ ▀███▀▀▀██▄ "
  echo  "██    ▀█  ██   ▀██▄  ██   ▀██▄▄██▀    ▀██▄ ██   ▀██▄"
  echo  "██   █    ██   ▄██   ██   ▄██ ██▀      ▀██ ██   ▄██ "
  echo  "██████    ███████    ███████  ██        ██ ███████"
  echo  "██   █  ▄ ██  ██▄    ██  ██▄  ██▄      ▄██ ██  ██▄"
  echo  "██     ▄█ ██   ▀██▄  ██   ▀██▄▀██▄    ▄██▀ ██   ▀██▄"
  echo "▄██████████████▄ ▄███▄████▄ ▄███▄ ▀▀████▀▀ ▄████▄ ▄███▄"
  echo ""
  echo "The commit message must have this format:"
  echo "<verb in imperative mood>: <what was done>"
  echo "Allowed verbs in imperative mood: build, chore, feat, fix, docs, refactor, perf, style, test"
  echo "Example: chore: Initial project"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
